export type SpinnerType = 'ball-scale-multiple'
  | 'ball-spin'
  | 'ball-spin-clockwise'
  | 'ball-spin-clockwise-fade-rotating'
  | 'ball-spin-fade-rotating'
  | 'chasing-dots'
  | 'circle'
  | 'cube-grid'
  | 'double-bounce'
  | 'fading-circle'
  | 'folding-cube'
  | 'pulse'
  | 'rectangle-bounce'
  | 'rectangle-bounce-party'
  | 'rectangle-bounce-pulse-out'
  | 'rectangle-bounce-pulse-out-rapid'
  | 'rotating-plane'
  | 'square-jelly-box'
  | 'square-loader'
  | 'three-bounce'
  | 'three-strings'
  | 'wandering-cubes';

export type DirectionType = 'ltr' | 'rtl';

export type PositionType = 'bottom-center'
  | 'bottom-left'
  | 'bottom-right'
  | 'center-center'
  | 'center-left'
  | 'center-right'
  | 'top-center'
  | 'top-left'
  | 'top-right';
