name: CI Testing

on:
  pull_request:
    branches:
      - master 
  
  push:
    branches:
      - master

jobs:
  test:
    name: Test on Node ${{ matrix.node-version }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable
          
      - name: Linting
        run: npm run lint
        
      - name: Build library
        run: npm run build:lib
        
      - name: Build schematics
        run: npm run build:schematics
        
      - name: Testing
        run: npm run test
        
      - name: Upload codecov report
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: false
          
      - name: Production build
        run: npm run build